# .github/workflows/build.yml
name: Build

on:
  push:
    branches:
      - main   # change this if you want other branches

jobs:
  build:
    runs-on: java_build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      # Uncomment if you want to upload artifacts
      # - name: Upload Build Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: jar
      #     path: target/*.jar
<<<<<<< HEAD

=======
        
    #   - name: Configure JFrog CLI
    # token
    #     run: |
    # check the curent jf config show and then delete it jf config rm name
    #         jfrog config add my-artifactory --url=https://trial42aeja.jfrog.io --apikey=${{ secrets.JFROG_TOKEN }}

    #checek current jfrog cofig and delete
>>>>>>> 73ce16631aa4ff219d9405e74d2a504174adb768
      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: https://trialgvt68y.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Upload JAR to JFrog
        run: |
          jf rt u "target/*.jar" "petjfrog-repo/"
