# .github/workflows/build.yml
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: https://trialgvt68y.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Verify JFrog connection
        run: jfrog rt ping

      - name: Debug JFrog Repo
        run: jfrog rt curl /api/repositories/petcho-libs-snapshot

      - name: Upload JAR to JFrog (Snapshot)
        run: |
          jfrog rt u "target/*.jar" "petcho-libs-snapshot/"
